# Generated by Django 5.0.3 on 2024-05-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simposio_app', '0002_remove_estudiante_qr_code_expositor_tema_a_impartir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='boleta_de_pago',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='imagen_boleta_pago',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numero_de_boleta',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expositor',
            name='tema_a_impartir',
            field=models.CharField(max_length=255),
        ),
    ]
