# Generated by Django 5.0.3 on 2024-05-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simposio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='expositor',
            name='tema_a_impartir',
            field=models.CharField(default='Tema por definir', max_length=255),
        ),
    ]
