# Generated by Django 4.1.4 on 2024-05-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simposio_app', '0006_estudiante_fecha_registro_expositor_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='expositor',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
