# Generated by Django 4.1.4 on 2024-05-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simposio_app', '0007_expositor_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expositor',
            name='qr_code',
        ),
    ]
