# Generated by Django 5.0.3 on 2024-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simposio_app', '0003_remove_estudiante_boleta_de_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='imagen_boleta_pago',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='boleta_de_pago',
            field=models.ImageField(default=1, upload_to='boletas_de_pago/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_de_boleta',
            field=models.CharField(max_length=30),
        ),
    ]
