# Generated by Django 5.0.3 on 2024-05-15 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simposio_app', '0005_estudiante_asistencia_estudiante_fecha_escaneo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expositor',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
